import random
import string

class AITestDataGenerator:
    """
    AI-inspired dynamic intelligent test data generation layer.
    Simulates LLM-powered test data generation for automation testing.
    """
    
    TITLES = [
        "Project Idea: {rand}",
        "Meeting Notes - {rand}",
        "Research: {rand} Study",
        "Reminder: Buy {rand}",
        "Draft: {rand} Strategy"
    ]
    
    DESCRIPTIONS = [
        "This note was generated by an AI model to test the {rand} functionality.",
        "System requirement: Ensure {rand} is implemented correctly in the next sprint.",
        "User feedback suggests that {rand} should be improved for better performance.",
        "Automatic validation of {rand} logic within the test framework.",
        "Critical path analysis for {rand} module development."
    ]

    @staticmethod
    def generate_note_data():
        """
        Generates dynamic note data including title and description.
        Returns a dictionary with 'title' and 'description'.
        """
        random_suffix = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
        
        title_template = random.choice(AITestDataGenerator.TITLES)
        desc_template = random.choice(AITestDataGenerator.DESCRIPTIONS)
        
        return {
            "title": title_template.format(rand=random_suffix),
            "description": desc_template.format(rand=random_suffix)
        }

    @staticmethod
    def generate_random_string(length=10):
        """Generates a random string of fixed length."""
        return ''.join(random.choices(string.ascii_letters + string.digits, k=length))
