import random
import string
import json
from utils.mcp_client import mcp_client
from utils.logger import logger

class AITestDataGenerator:
    """
    AI-powered dynamic intelligent test data generation layer.
    Uses LLM for realistic and diverse test data.
    """
    
    # Fallback static data
    TITLES = [
        "Project Idea: {rand}",
        "Meeting Notes - {rand}",
        "Research: {rand} Study"
    ]
    
    DESCRIPTIONS = [
        "This note was generated by an AI model to test the {rand} functionality.",
        "System requirement: Ensure {rand} is implemented correctly."
    ]

    @staticmethod
    def generate_note_data():
        """
        Generates dynamic note data using LLM with fallback.
        """
        random_suffix = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
        
        # Try LLM first
        llm_data = mcp_client.generate_data(
            context_type="Note Application",
            requirements="A title and a description for a personal note. Use diverse topics."
        )
        
        if llm_data:
            try:
                # Basic sanitization for JSON
                if "```json" in llm_data:
                    llm_data = llm_data.split("```json")[1].split("```")[0].strip()
                
                data = json.loads(llm_data)
                if "title" in data and "description" in data:
                    logger.info("Generated test data using LLM.")
                    return data
            except Exception as e:
                logger.warning(f"Failed to parse LLM data: {e}. Falling back to static data.")

        # Fallback to static templates
        title_template = random.choice(AITestDataGenerator.TITLES)
        desc_template = random.choice(AITestDataGenerator.DESCRIPTIONS)
        
        return {
            "title": title_template.format(rand=random_suffix),
            "description": desc_template.format(rand=random_suffix)
        }

    @staticmethod
    def generate_random_string(length=10):
        """Generates a random string of fixed length."""
        return ''.join(random.choices(string.ascii_letters + string.digits, k=length))
